### ISSUE TITLE
CPU Cores/Threads limited to 32

### ISSUE THREAD

**Issue by HEEROCKSS** [principat/sheepit-client#2]
I noticed that your Client Fork limits CPU Cores/Threads to 32.
My PC has two CPU`s with 12C/24T each = 24 Cores and 48 Threads.

I really would like to use your Client with this PC and can run it with all 48 Threads.

Cheers

**Comment by principat** [comment]
Hi thanks for the response. This limitation does not come from my fork but would analysis it. Meanwhile you could use more instances of the client to use the full power of you computer.
Could you tell me which os you are using?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 10.03.17, 14:05, HEEROCKSS <notifications@github.com> schrieb:

  
    
      I noticed that your Client Fork limits CPU Cores/Threads to 32.
      My PC has two CPU`s with 12C/24T each = 24 Cores and 48 Threads.
    
    
      I really would like to use your Client with this PC and can run it with all 48 Threads.
    
    
      Cheers

**Comment by HEEROCKSS** [comment]
I just thought it comes from your Fork because with the normal Client from Laurent i can utilize all cores. 
The PC runs on Windows 10 Pro. 
Thank you for the advise with multiple instances!

**Comment by principat** [comment]
i analysed my code and could not found a limitation for the number of cores.
could you try it with my latest release,

**Comment by HEEROCKSS** [comment]
Ok i am confused now... you did no changes to version 1.8? Because now it works, even though when i opened this Issue, i used the same Version and it did not work!
This PC (Server) runs 24/7, there were no updates, not even a simple reboot since i opened this Issue nor any software installations/changes...

Im really sorry for this false alert >.< 
Anyway, thank you for this awesome Fork and your Time!

**Comment by principat** [comment]
thanks for the info that this is a false alert.
